# Setup
title:            LRG
tagline:          'LRG Research Group'
description:      'Low-Dimensional Materials and Devices Research Group'
url:              http://www.lrgresearch.org
baseurl:          /

author:
  name:           'SBLisesivdin'
  url:            http://sblisesivdin.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/lrgresearch
